### ISSUE TITLE
build_node_compilers is incompatible with the latest build_runner

### ISSUE THREAD

**Issue by lexaknyazev** [pulyaevskiy/node-interop#54]
Starting with version 1.2.4, `build_runner` depends on `analyzer: ^0.35.0`.
Yet, `build_node_compilers` depends on `analyzer: ">=0.30.0 <0.35.0"`.

**Comment by lexaknyazev** [comment]
@pulyaevskiy 
Would it be possible to upgrade the `build_node_compilers` so that it works with the latest `build_runner` and `build_modules` packages?

**Comment by alextekartik** [comment]
This issue also actually prevents running on dart 2.5.0-dev

**Comment by alextekartik** [comment]
It now prevents from running on stable 2.5.0

**Comment by pulyaevskiy** [comment]
I started looking into this last night, hopefully will have an update soon.

**Comment by pulyaevskiy** [comment]
https://github.com/pulyaevskiy/node-interop/pull/66 should generally work with dart 2.5.0 and latest build dependencies. Haven't merged it yet because I wanted to run more tests. Feel free to try it out in your projects and let me know how it works for you!

**Comment by alextekartik** [comment]
Perfect. I have tried with the following override dependency:

```yaml
  build_node_compilers:
    git:
      url: git://github.com/pulyaevskiy/node-interop
      path: build_node_compilers
      ref: upgrade-compilers-to-dart-2.5.0
```

Just a `pub get` did not fix the issue, I had to do a `pub upgrade` so that `stream_channel` get updated to 2.0.0 (and others) and my [test](https://travis-ci.org/tekartik/platform.dart) works fine. (well it is still failing on travis but should succeed as soon as you release a new version on pub).

Thanks!
