### ISSUE TITLE
Building with dart2js ignores pubspec.yaml transformers options

### ISSUE THREAD

**Issue by TonyDowney** [pulyaevskiy/node-interop#7]
pubspec.yaml:
`transformers:`
`  - $dart2js:`
`    commandLineOptions: [--use-old-frontend]`

Running the build command:
`pub run build_runner build --define="build_node_compilers|entrypoint=compiler=dart2js" --output=build/`

It ignores the commandLineOptions for dart2js. As a result all dart2js builds are failing in Dart SDK `^2.0.0-dev.37.0`, at least until this Dart SDK bug is resolved: https://github.com/dart-lang/sdk/issues/32547

**Comment by pulyaevskiy** [comment]
`build_runner` system effectively replaces Pub's transformers so it is not supposed to read transformers config from Pubspec.

You can supply arguments to dart2js via `dart2js_args` setting. See example in [firebase functions interop](https://github.com/pulyaevskiy/firebase-functions-interop/blob/master/functions/build.yaml): 

```yaml
targets:
  $default:
    sources:
      - "node/**"
      - "lib/**"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
        - node/**
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
          - --checked
          - --use-old-frontend # the new flag goes here
```

Or via command line:

```bash
pub run build_runner build \
  --define="build_node_compilers|entrypoint=compiler=dart2js" \
  --define="build_node_compilers|entrypoint=dart2js_args=[\"--checked\", \"--use-old-frontend\"]"  \
  --output=build/
```
