### ISSUE TITLE
Build fails without "lib/**"

### ISSUE THREAD

**Issue by yoshi12u** [pulyaevskiy/node-interop#76]
Build with build_node_compilers fails without "lib/**" under build sources, even if there is no directory named "lib".
## Reproduction:
Make a new directory and put three files below.
```yaml
# pubspec.yaml
name: reproduction
description: reproduction

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0
```

```yaml
# build.yaml
targets:
  $default:
    sources:
      - "example/**"
```

```dart
// example/hello_world.dart
void main() {
  print('Hello World!');
}
```

Now, run `pub run build_runner build --output=build/ `. It will fail.
Then, add `- "lib/**"` to your build sources and run build command again. It will pass.
