### ISSUE TITLE
Use new front-end with Dart2JS

### ISSUE THREAD

**Issue by Cretezy** [pulyaevskiy/node-interop#8]
`build_web_compilers` recently broke with `2.0.0-dev.37`. These were the commits that fixed it:

* https://github.com/dart-lang/build/pull/1172
* https://github.com/dart-lang/build/pull/1180

The simple fix until `build_node_compilers` is fixed is to add `--use-old-frontend` to your Dart2JS options in the `build.yaml`.

**Comment by Cretezy** [comment]
https://github.com/pulyaevskiy/node-interop/pull/9 for temp fix.

**Comment by Cretezy** [comment]
https://github.com/Cretezy/node-interop/tree/new-frontend for future fix when [`scratch_space`](https://pub.dartlang.org/packages/scratch_space) publishes `0.2.0`.

**Comment by daniel-v** [comment]
Mentioned pull request seems to do the trick. 

```
Dart VM version: 2.0.0-dev.39.0 (Fri Mar 16 00:17:07 2018 +0100) on "linux_x64"
node_interop-1.0.0-dev.6.0
```

Until it is merged, here is a sample build.yaml

```yaml
targets:
  $default:
    sources:
      - "node/**.dart"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
        - node/**.dart
        options:
          compiler: dart2js
          dart2js_args:
          - --use-old-frontend
```

invoke with `pub run build_runner build node`
